@extends('layouts.app')

@section('content')
<style>
    .version-report-hero{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:22px}.version-report-hero h2{margin:4px 0;font-weight:800;color:#123d37}.version-report-hero p{margin:0;color:#71837e}.version-report-hero .btn{display:inline-flex;align-items:center;gap:7px;min-height:44px;border-radius:9px;font-weight:700}
    .version-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:22px}.version-stat{display:flex;align-items:center;gap:13px;padding:18px;background:#fff;border:1px solid #dce9e5;border-radius:12px;box-shadow:0 5px 18px rgba(20,66,58,.05)}.version-stat-icon{display:grid;place-items:center;flex:0 0 44px;height:44px;border-radius:11px;background:#e8f6f3;color:#008f85}.version-stat strong{display:block;color:#113b35;font-size:24px;line-height:1}.version-stat small{display:block;margin-top:6px;color:#768782}.version-stat.derived .version-stat-icon{background:#eef0ff;color:#5964b3}.version-stat.effective .version-stat-icon{background:#e8f6eb;color:#328247}.version-stat.roots .version-stat-icon{background:#fff3df;color:#a66a08}
    .version-table-card{border:0;border-radius:15px;overflow:hidden;box-shadow:0 8px 26px rgba(20,66,58,.07)}.version-table-card .card-header{display:flex;justify-content:space-between;align-items:center;padding:17px 20px;background:linear-gradient(90deg,#edf7f4,#fff);border-bottom:1px solid #dce8e4}.version-table-card .card-header h5{margin:0;color:#123d37;font-weight:750}
    .version-register-head,.version-register-row{display:grid;grid-template-columns:minmax(300px,2.2fr) minmax(105px,.55fr) minmax(135px,.72fr) minmax(150px,.85fr) minmax(185px,1fr) auto;gap:16px;align-items:center}.version-register-head{padding:12px 18px;background:#eaf4f1;color:#496a64;font-size:10px;font-weight:750;text-transform:uppercase;letter-spacing:.065em}.version-register-row{position:relative;padding:15px 18px;border-bottom:1px solid #e6efec;background:#fff;transition:.18s}.version-register-row:last-child{border-bottom:0}.version-register-row:hover{z-index:1;background:#f7fcfa;box-shadow:inset 4px 0 #009c92}.version-title{display:flex;align-items:center;gap:11px;min-width:0;color:inherit}.version-title:hover{color:#008f85}.version-title-icon{display:grid;place-items:center;flex:0 0 40px;height:40px;border-radius:10px;background:#e8f6f3;color:#008f85}.version-title-copy{min-width:0}.version-title strong,.version-title small{display:block}.version-title strong{display:-webkit-box;overflow:hidden;color:#123d37;font-size:12px;line-height:1.35;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow-wrap:anywhere}.version-title small{margin-top:3px;color:#85938f}.version-number{display:inline-flex;align-items:center;gap:5px;font-weight:800;color:#123d37}.version-cell-label{display:none;margin-bottom:3px;color:#72857f;font-size:9px;font-weight:750;text-transform:uppercase;letter-spacing:.06em}.release-meta strong,.release-meta small,.publisher-meta strong,.publisher-meta small{display:block}.release-meta small,.publisher-meta small{margin-top:3px;color:#85938f;font-size:10px}.publisher-meta strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#244b44;font-size:11px}.effective-badge,.lineage-badge{display:inline-flex;align-items:center;gap:4px;padding:5px 8px;border-radius:20px;font-size:10px;font-weight:750}.effective-badge{margin-top:5px;background:#e4f5e8;color:#28753c}.lineage-badge{background:#edf5f3;color:#3c685f;white-space:nowrap}.lineage-badge.derived{background:#efeffd;color:#595da0}.version-action{display:grid;place-items:center;width:36px;height:36px;padding:0;border-radius:9px}.empty-version-report{text-align:center;padding:65px 20px;color:#7d908b}.empty-version-report .material-icons{font-size:48px;color:#9bb0aa}
    @media(max-width:1199px){.version-register-head{display:none}.version-register-row{grid-template-columns:minmax(260px,1.6fr) repeat(3,minmax(120px,.7fr)) auto}.version-register-row .lineage-cell{display:none}.version-cell-label{display:block}}
    @media(max-width:991px){.version-stats{grid-template-columns:repeat(2,1fr)}.version-report-hero{align-items:flex-start;flex-direction:column}.version-register-row{grid-template-columns:minmax(0,1fr) minmax(115px,.42fr) minmax(135px,.5fr) auto}.version-register-row .publisher-cell{display:none}}
    @media(max-width:767px){.version-register-row{grid-template-columns:1fr 1fr;gap:12px}.version-title{grid-column:1/-1}.version-action-cell{position:absolute;right:14px;top:16px}.version-title-copy{padding-right:38px}.version-register-row .publisher-cell{display:block}}
    @media(max-width:575px){.version-stats{grid-template-columns:1fr}.version-report-hero .btn{width:100%;justify-content:center}.version-register-row{grid-template-columns:1fr}.version-title{grid-column:auto}.version-action-cell{right:10px;top:12px}.version-register-row .lineage-cell{display:block}}
</style>

<div class="breadcrumb-flow"><a href="{{ route('dashboard') }}">Dashboard</a><span class="material-icons">chevron_right</span><span>Versioning report</span></div>
<div class="version-report-hero">
    <div><span class="eyebrow">Document lifecycle intelligence</span><h2>Versioning Report</h2><p>Trace root documents, derived revisions, publishers, and each effective release.</p></div>
    <a href="{{ route('policy-documents.index') }}" class="btn btn-secondary"><span class="material-icons">folder_open</span>Open document repository</a>
</div>

<div class="version-stats">
    <div class="version-stat"><span class="version-stat-icon material-icons">history</span><div><strong>{{ $versionStats['records'] }}</strong><small>Total version records</small></div></div>
    <div class="version-stat roots"><span class="version-stat-icon material-icons">account_tree</span><div><strong>{{ $versionStats['roots'] }}</strong><small>Root documents</small></div></div>
    <div class="version-stat derived"><span class="version-stat-icon material-icons">difference</span><div><strong>{{ $versionStats['derived'] }}</strong><small>Derived versions</small></div></div>
    <div class="version-stat effective"><span class="version-stat-icon material-icons">verified</span><div><strong>{{ $versionStats['effective'] }}</strong><small>Effective releases</small></div></div>
</div>

<div class="card version-table-card">
    <div class="card-header"><h5>Version register</h5><small class="text-muted">{{ $documents->count() }} accessible record{{ $documents->count() === 1 ? '' : 's' }}</small></div>
    <div class="version-register">
        <div class="version-register-head"><span>Document</span><span>Version</span><span>Effective release</span><span>Status &amp; type</span><span>Publisher</span><span>View</span></div>
        @forelse($documents as $document)
            <article class="version-register-row">
                <a class="version-title" href="{{ route('policy-documents.show', $document) }}"><span class="version-title-icon material-icons">{{ $document->document_type === 'circular' ? 'campaign' : 'description' }}</span><span class="version-title-copy"><strong>{{ $document->title }}</strong><small>{{ $document->reference_number ?: 'No official reference' }}</small></span></a>
                <div><span class="version-cell-label">Version</span><span class="version-number"><span class="material-icons" style="font-size:16px">history</span>v{{ $document->version_number }}</span>@if($document->is_effective_published_version)<div><span class="effective-badge"><span class="material-icons" style="font-size:12px">check_circle</span>Effective</span></div>@endif</div>
                <div class="release-meta"><span class="version-cell-label">Effective release</span>@if($document->effective_version_number)<strong>v{{ $document->effective_version_number }}</strong><small>Current published</small>@else<span class="text-muted">Not published</span>@endif</div>
                <div><span class="version-cell-label">Status &amp; type</span><span class="status-pill status-{{ $document->status }}">{{ $document->statusLabel() }}</span><div class="mt-1"><span class="soft-badge">{{ ucfirst($document->document_type) }}</span></div></div>
                <div class="publisher-meta publisher-cell"><span class="version-cell-label">Publisher</span><strong>{{ $document->publisher?->name ?? 'Not published' }}</strong><small>{{ $document->published_at?->format('d M Y H:i') ?? 'No publication date' }}</small><div class="lineage-cell mt-1"><span class="lineage-badge {{ $document->parent_document_id ? 'derived' : '' }}"><span class="material-icons" style="font-size:13px">{{ $document->parent_document_id ? 'call_split' : 'hub' }}</span>{{ $document->parent_document_id ? 'Derived version' : 'Root record' }}</span></div></div>
                <div class="version-action-cell"><a href="{{ route('policy-documents.show', $document) }}" class="btn btn-info version-action" title="View {{ $document->title }}" aria-label="View {{ $document->title }}"><span class="material-icons" style="font-size:18px">visibility</span></a></div>
            </article>
        @empty
            <div class="empty-version-report"><span class="material-icons">history_toggle_off</span><h5>No version data available</h5><p>No accessible document versions have been registered.</p></div>
        @endforelse
    </div>
</div>
@endsection
